{"uuid": "ff0f71a7-3af6-4e69-b55c-65b3c968dc24", "children": ["58c90a6f-61c8-4f8c-a447-94016f6dfba4"], "befores": [{"name": "browser_management", "status": "passed", "start": 1668590187422, "stop": 1668590198337}], "afters": [{"name": "browser_management::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=107.0.5304.110)\nStacktrace:\n#0 0x561a073b8463 <unknown>\n#1 0x561a0717c8d8 <unknown>\n#2 0x561a07158a50 <unknown>\n#3 0x561a071df84d <unknown>\n#4 0x561a071f38d9 <unknown>\n#5 0x561a071db443 <unknown>\n#6 0x561a071ac3c5 <unknown>\n#7 0x561a071ad531 <unknown>\n#8 0x561a0740adce <unknown>\n#9 0x561a0740e192 <unknown>\n#10 0x561a073ef93e <unknown>\n#11 0x561a0740f103 <unknown>\n#12 0x561a073e2d85 <unknown>\n#13 0x561a074300a8 <unknown>\n#14 0x561a07430239 <unknown>\n#15 0x561a0744b492 <unknown>\n#16 0x7fbc9ebabb43 <unknown>\n\n", "trace": "  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/allure_commons/_allure.py\", line 209, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"/home/vlad/PycharmProjects/Codarium_course/todomvc_test/tests/conftest.py\", line 19, in browser_management\n    browser.clear_local_storage()\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selene/core/entity.py\", line 1620, in clear_local_storage\n    self.driver.execute_script(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 884, in execute_script\n    return self.execute(command, {\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668590206347, "stop": 1668590206554}], "start": 1668590187422, "stop": 1668590206554}